### ISSUE TITLE
#pytorchlightning-version

### ISSUE THREAD

**Issue by skiller9** [JusperLee/TDANet#13]
Hi, Jusper. I came across the following issue when i used the code you provided. Maybe it's the pytorchlightning version problem, could you show me the requirements of your code?
![微信截图_202310081035131](https://github.com/JusperLee/TDANet/assets/145819885/cc5f17b4-9041-4718-81d3-346511016f1d)

**Comment by JusperLee** [comment]
pytorch-lightning           2.0.9.post0
torch                       1.13.1+cu116

**Comment by skiller9** [comment]
I have the same requirements with you, could you give some suggestion to solve the issue i met with?
![微信截图_20231018110206](https://github.com/JusperLee/TDANet/assets/145819885/594f9cb2-0bb4-4bee-a916-ef619eb76f12)
![微信截图_20231018110230](https://github.com/JusperLee/TDANet/assets/145819885/ff40f2ae-87c7-4074-8d5a-12c91d2a7c35)

**Comment by JusperLee** [comment]
I've encountered similar errors in the past. It appears there's a RuntimeError in your DataLoader worker process. This can be caused by several reasons:

1. Make sure you have enough memory available, as DataLoader processes can be memory-intensive.
2. Ensure that your dataset returns items correctly and doesn't have any underlying issues that might cause a process to fail.
3. Try reducing the number of workers in the DataLoader, or set `num_workers=0` to see if the problem persists.

If you could provide more details or share the exact error message the DataLoader is raising, it might help in pinpointing the problem more accurately.

**Comment by skiller9** [comment]
Thank for your quick answer. I will try your advice and give my feedback.
