### ISSUE TITLE
Test-loss

### ISSUE THREAD

**Issue by gnorZgnoD** [JusperLee/TDANet#15]
Hi, Jusper, i added noise output based on your model, and now the output of the model are speaker one , speaker two and noise. But how can i change the test loss, let the loss won't calculate the noise si-snr-i into total si-snr-i? looking forward for your reply.
![image](https://github.com/JusperLee/TDANet/assets/105347776/c6982e70-4e14-4455-99f1-f55d1361c44e)

.

**Comment by JusperLee** [comment]
Thank you for reaching out with your question. If you want to modify the test loss so that it doesn't include the SI-SNR-I for noise, you can simply remove the noise dimension from the input. By doing this, the model will not consider the noise component when calculating the total SI-SNR-I, thus effectively excluding it from the loss calculation. Hope this helps, and if you have any more questions or need further clarification, feel free to ask.
